# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'B4UdigNL.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from qgis.gui import QgsColorButton

class Ui_B4UdigNL(object):
    def setupUi(self, B4UdigNL):
        B4UdigNL.setObjectName("B4UdigNL")
        B4UdigNL.resize(324, 432)
        B4UdigNL.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.verticalLayout = QtWidgets.QVBoxLayout(B4UdigNL)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(B4UdigNL)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.messageTab = QtWidgets.QWidget()
        self.messageTab.setObjectName("messageTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.messageTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.messageBox = QtWidgets.QGroupBox(self.messageTab)
        self.messageBox.setObjectName("messageBox")
        self.gridLayout = QtWidgets.QGridLayout(self.messageBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openMsgButton = QtWidgets.QPushButton(self.messageBox)
        self.openMsgButton.setObjectName("openMsgButton")
        self.horizontalLayout.addWidget(self.openMsgButton)
        self.openArchiveButton = QtWidgets.QPushButton(self.messageBox)
        self.openArchiveButton.setObjectName("openArchiveButton")
        self.horizontalLayout.addWidget(self.openArchiveButton)
        spacerItem = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.msgListWidget = QtWidgets.QListWidget(self.messageBox)
        self.msgListWidget.setMinimumSize(QtCore.QSize(100, 40))
        self.msgListWidget.setMaximumSize(QtCore.QSize(16777215, 60))
        self.msgListWidget.setObjectName("msgListWidget")
        self.gridLayout.addWidget(self.msgListWidget, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gotoButton = QtWidgets.QPushButton(self.messageBox)
        self.gotoButton.setObjectName("gotoButton")
        self.horizontalLayout_2.addWidget(self.gotoButton)
        self.bestScaleButton = QtWidgets.QPushButton(self.messageBox)
        self.bestScaleButton.setObjectName("bestScaleButton")
        self.horizontalLayout_2.addWidget(self.bestScaleButton)
        self.removeMsgButton = QtWidgets.QPushButton(self.messageBox)
        self.removeMsgButton.setObjectName("removeMsgButton")
        self.horizontalLayout_2.addWidget(self.removeMsgButton)
        spacerItem1 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.messageBox)
        self.additionsBox = QtWidgets.QGroupBox(self.messageTab)
        self.additionsBox.setMaximumSize(QtCore.QSize(16777215, 300))
        self.additionsBox.setObjectName("additionsBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.additionsBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeWidget = QtWidgets.QTreeWidget(self.additionsBox)
        self.treeWidget.setMinimumSize(QtCore.QSize(100, 100))
        self.treeWidget.setMaximumSize(QtCore.QSize(16777215, 250))
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.gridLayout_2.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.openDocButton = QtWidgets.QPushButton(self.additionsBox)
        self.openDocButton.setObjectName("openDocButton")
        self.horizontalLayout_3.addWidget(self.openDocButton)
        spacerItem2 = QtWidgets.QSpacerItem(168, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.additionsBox)
        spacerItem3 = QtWidgets.QSpacerItem(17, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.saveButton = QtWidgets.QPushButton(self.messageTab)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_4.addWidget(self.saveButton)
        spacerItem4 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.helpButton = QtWidgets.QPushButton(self.messageTab)
        self.helpButton.setObjectName("helpButton")
        self.horizontalLayout_4.addWidget(self.helpButton)
        self.closeButton = QtWidgets.QPushButton(self.messageTab)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_4.addWidget(self.closeButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.messageTab, "")
        self.ThemesTab = QtWidgets.QWidget()
        self.ThemesTab.setObjectName("ThemesTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ThemesTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.mColorButton = QgsColorButton(self.ThemesTab)
        self.mColorButton.setMinimumSize(QtCore.QSize(40, 10))
        self.mColorButton.setMaximumSize(QtCore.QSize(40, 10))
        self.mColorButton.setAcceptDrops(False)
        self.mColorButton.setColor(QtGui.QColor(0, 255, 0))
        self.mColorButton.setShowMenu(False)
        self.mColorButton.setProperty("acceptLiveUpdates", False)
        self.mColorButton.setObjectName("mColorButton")
        self.horizontalLayout_5.addWidget(self.mColorButton)
        self.checkBoxData = QtWidgets.QCheckBox(self.ThemesTab)
        self.checkBoxData.setTristate(True)
        self.checkBoxData.setObjectName("checkBoxData")
        self.horizontalLayout_5.addWidget(self.checkBoxData)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.refreshButton = QtWidgets.QPushButton(self.ThemesTab)
        self.refreshButton.setObjectName("refreshButton")
        self.gridLayout_3.addWidget(self.refreshButton, 0, 1, 2, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.mColorButton_2 = QgsColorButton(self.ThemesTab)
        self.mColorButton_2.setMinimumSize(QtCore.QSize(40, 10))
        self.mColorButton_2.setMaximumSize(QtCore.QSize(40, 10))
        self.mColorButton_2.setAcceptDrops(False)
        self.mColorButton_2.setColor(QtGui.QColor(255, 215, 80))
        self.mColorButton_2.setShowMenu(False)
        self.mColorButton_2.setProperty("acceptLiveUpdates", False)
        self.mColorButton_2.setObjectName("mColorButton_2")
        self.horizontalLayout_6.addWidget(self.mColorButton_2)
        self.checkBoxGas_low = QtWidgets.QCheckBox(self.ThemesTab)
        self.checkBoxGas_low.setTristate(True)
        self.checkBoxGas_low.setObjectName("checkBoxGas_low")
        self.horizontalLayout_6.addWidget(self.checkBoxGas_low)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.mColorButton_3 = QgsColorButton(self.ThemesTab)
        self.mColorButton_3.setMinimumSize(QtCore.QSize(40, 10))
        self.mColorButton_3.setMaximumSize(QtCore.QSize(40, 10))
        self.mColorButton_3.setAcceptDrops(False)
        self.mColorButton_3.setColor(QtGui.QColor(255, 175, 60))
        self.mColorButton_3.setShowMenu(False)
        self.mColorButton_3.setProperty("acceptLiveUpdates", False)
        self.mColorButton_3.setObjectName("mColorButton_3")
        self.horizontalLayout_7.addWidget(self.mColorButton_3)
        self.checkBoxGas_high = QtWidgets.QCheckBox(self.ThemesTab)
        self.checkBoxGas_high.setTristate(True)
        self.checkBoxGas_high.setObjectName("checkBoxGas_high")
        self.horizontalLayout_7.addWidget(self.checkBoxGas_high)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 2, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.mColorButton_4 = QgsColorButton(self.ThemesTab)
        self.mColorButton_4.setMinimumSize(QtCore.QSize(40, 10))
        self.mColorButton_4.setMaximumSize(QtCore.QSize(40, 10))
        self.mColorButton_4.setAcceptDrops(False)
        self.mColorButton_4.setColor(QtGui.QColor(255, 127, 0))
        self.mColorButton_4.setShowMenu(False)
        self.mColorButton_4.setProperty("acceptLiveUpdates", False)
        self.mColorButton_4.setObjectName("mColorButton_4")
        self.horizontalLayout_8.addWidget(self.mColorButton_4)
        self.checkBoxDanger = QtWidgets.QCheckBox(self.ThemesTab)
        self.checkBoxDanger.setTristate(True)
        self.checkBoxDanger.setObjectName("checkBoxDanger")
        self.horizontalLayout_8.addWidget(self.checkBoxDanger)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 3, 0, 1, 2)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.mColorButton_8 = QgsColorButton(self.ThemesTab)
        self.mColorButton_8.setMinimumSize(QtCore.QSize(40, 10))
        self.mColorButton_8.setMaximumSize(QtCore.QSize(40, 10))
        self.mColorButton_8.setAcceptDrops(False)
        self.mColorButton_8.setColor(QtGui.QColor(255, 0, 0))
        self.mColorButton_8.setShowMenu(False)
        self.mColorButton_8.setProperty("acceptLiveUpdates", False)
        self.mColorButton_8.setObjectName("mColorButton_8")
        self.horizontalLayout_20.addWidget(self.mColorButton_8)
        self.checkBoxElec_land = QtWidgets.QCheckBox(self.ThemesTab)
        self.checkBoxElec_land.setTristate(True)
        self.checkBoxElec_land.setObjectName("checkBoxElec_land")
        self.horizontalLayout_20.addWidget(self.checkBoxElec_land)
        self.gridLayout_3.addLayout(self.horizontalLayout_20, 4, 0, 1, 2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.mColorButton_7 = QgsColorButton(self.ThemesTab)
        self.mColorButton_7.setMinimumSize(QtCore.QSize(40, 10))
        self.mColorButton_7.setMaximumSize(QtCore.QSize(40, 10))
        self.mColorButton_7.setAcceptDrops(False)
        self.mColorButton_7.setColor(QtGui.QColor(255, 0, 0))
        self.mColorButton_7.setShowMenu(False)
        self.mColorButton_7.setProperty("acceptLiveUpdates", False)
        self.mColorButton_7.setObjectName("mColorButton_7")
        self.horizontalLayout_11.addWidget(self.mColorButton_7)
        self.checkBoxElec_high = QtWidgets.QCheckBox(self.ThemesTab)
        self.checkBoxElec_high.setTristate(True)
        self.checkBoxElec_high.setObjectName("checkBoxElec_high")
        self.horizontalLayout_11.addWidget(self.checkBoxElec_high)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 5, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.mColorButton_6 = QgsColorButton(self.ThemesTab)
        self.mColorButton_6.setMinimumSize(QtCore.QSize(40, 10))
        self.mColorButton_6.setMaximumSize(QtCore.QSize(40, 10))
        self.mColorButton_6.setAcceptDrops(False)
        self.mColorButton_6.setColor(QtGui.QColor(200, 0, 0))
        self.mColorButton_6.setShowMenu(False)
        self.mColorButton_6.setProperty("acceptLiveUpdates", False)
        self.mColorButton_6.setObjectName("mColorButton_6")
        self.horizontalLayout_10.addWidget(self.mColorButton_6)
        self.checkBoxElec_mid = QtWidgets.QCheckBox(self.ThemesTab)
        self.checkBoxElec_mid.setTristate(True)
        self.checkBoxElec_mid.setObjectName("checkBoxElec_mid")
        self.horizontalLayout_10.addWidget(self.checkBoxElec_mid)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 6, 0, 1, 2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.mColorButton_5 = QgsColorButton(self.ThemesTab)
        self.mColorButton_5.setMinimumSize(QtCore.QSize(40, 10))
        self.mColorButton_5.setMaximumSize(QtCore.QSize(40, 10))
        self.mColorButton_5.setAcceptDrops(False)
        self.mColorButton_5.setColor(QtGui.QColor(150, 0, 0))
        self.mColorButton_5.setShowMenu(False)
        self.mColorButton_5.setObjectName("mColorButton_5")
        self.horizontalLayout_9.addWidget(self.mColorButton_5)
        self.checkBoxElec_low = QtWidgets.QCheckBox(self.ThemesTab)
        self.checkBoxElec_low.setTristate(True)
        self.checkBoxElec_low.setObjectName("checkBoxElec_low")
        self.horizontalLayout_9.addWidget(self.checkBoxElec_low)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 7, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.mColorButton_13 = QgsColorButton(self.ThemesTab)
        self.mColorButton_13.setMinimumSize(QtCore.QSize(40, 10))
        self.mColorButton_13.setMaximumSize(QtCore.QSize(40, 10))
        self.mColorButton_13.setAcceptDrops(False)
        self.mColorButton_13.setColor(QtGui.QColor(182, 74, 0))
        self.mColorButton_13.setShowMenu(False)
        self.mColorButton_13.setProperty("acceptLiveUpdates", False)
        self.mColorButton_13.setObjectName("mColorButton_13")
        self.horizontalLayout_16.addWidget(self.mColorButton_13)
        self.checkBoxChemical = QtWidgets.QCheckBox(self.ThemesTab)
        self.checkBoxChemical.setTristate(True)
        self.checkBoxChemical.setObjectName("checkBoxChemical")
        self.horizontalLayout_16.addWidget(self.checkBoxChemical)
        self.gridLayout_3.addLayout(self.horizontalLayout_16, 8, 0, 1, 1)
        self.vectorCheckBox = QtWidgets.QCheckBox(self.ThemesTab)
        self.vectorCheckBox.setObjectName("vectorCheckBox")
        self.gridLayout_3.addWidget(self.vectorCheckBox, 8, 1, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.mColorButton_9 = QgsColorButton(self.ThemesTab)
        self.mColorButton_9.setMinimumSize(QtCore.QSize(40, 10))
        self.mColorButton_9.setMaximumSize(QtCore.QSize(40, 10))
        self.mColorButton_9.setAcceptDrops(False)
        self.mColorButton_9.setColor(QtGui.QColor(186, 56, 168))
        self.mColorButton_9.setShowMenu(False)
        self.mColorButton_9.setObjectName("mColorButton_9")
        self.horizontalLayout_12.addWidget(self.mColorButton_9)
        self.checkBoxSewer_free = QtWidgets.QCheckBox(self.ThemesTab)
        self.checkBoxSewer_free.setTristate(True)
        self.checkBoxSewer_free.setObjectName("checkBoxSewer_free")
        self.horizontalLayout_12.addWidget(self.checkBoxSewer_free)
        self.gridLayout_3.addLayout(self.horizontalLayout_12, 9, 0, 1, 1)
        self.rasterCheckBox = QtWidgets.QCheckBox(self.ThemesTab)
        self.rasterCheckBox.setEnabled(True)
        self.rasterCheckBox.setObjectName("rasterCheckBox")
        self.gridLayout_3.addWidget(self.rasterCheckBox, 9, 1, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.mColorButton_10 = QgsColorButton(self.ThemesTab)
        self.mColorButton_10.setMinimumSize(QtCore.QSize(40, 10))
        self.mColorButton_10.setMaximumSize(QtCore.QSize(40, 10))
        self.mColorButton_10.setAcceptDrops(False)
        self.mColorButton_10.setColor(QtGui.QColor(128, 0, 128))
        self.mColorButton_10.setShowMenu(False)
        self.mColorButton_10.setProperty("acceptLiveUpdates", False)
        self.mColorButton_10.setObjectName("mColorButton_10")
        self.horizontalLayout_13.addWidget(self.mColorButton_10)
        self.checkBoxSewer_pressure = QtWidgets.QCheckBox(self.ThemesTab)
        self.checkBoxSewer_pressure.setTristate(True)
        self.checkBoxSewer_pressure.setObjectName("checkBoxSewer_pressure")
        self.horizontalLayout_13.addWidget(self.checkBoxSewer_pressure)
        self.gridLayout_3.addLayout(self.horizontalLayout_13, 10, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.mColorButton_11 = QgsColorButton(self.ThemesTab)
        self.mColorButton_11.setMinimumSize(QtCore.QSize(40, 10))
        self.mColorButton_11.setMaximumSize(QtCore.QSize(40, 10))
        self.mColorButton_11.setAcceptDrops(False)
        self.mColorButton_11.setColor(QtGui.QColor(0, 128, 128))
        self.mColorButton_11.setShowMenu(False)
        self.mColorButton_11.setObjectName("mColorButton_11")
        self.horizontalLayout_14.addWidget(self.mColorButton_11)
        self.checkBoxHeat = QtWidgets.QCheckBox(self.ThemesTab)
        self.checkBoxHeat.setTristate(True)
        self.checkBoxHeat.setObjectName("checkBoxHeat")
        self.horizontalLayout_14.addWidget(self.checkBoxHeat)
        self.gridLayout_3.addLayout(self.horizontalLayout_14, 11, 0, 1, 1)
        self.annotationCheckBox = QtWidgets.QCheckBox(self.ThemesTab)
        self.annotationCheckBox.setTristate(True)
        self.annotationCheckBox.setObjectName("annotationCheckBox")
        self.gridLayout_3.addWidget(self.annotationCheckBox, 11, 1, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.mColorButton_12 = QgsColorButton(self.ThemesTab)
        self.mColorButton_12.setMinimumSize(QtCore.QSize(40, 10))
        self.mColorButton_12.setMaximumSize(QtCore.QSize(40, 10))
        self.mColorButton_12.setAcceptDrops(False)
        self.mColorButton_12.setColor(QtGui.QColor(0, 0, 255))
        self.mColorButton_12.setShowMenu(False)
        self.mColorButton_12.setObjectName("mColorButton_12")
        self.horizontalLayout_15.addWidget(self.mColorButton_12)
        self.checkBoxWater = QtWidgets.QCheckBox(self.ThemesTab)
        self.checkBoxWater.setTristate(True)
        self.checkBoxWater.setObjectName("checkBoxWater")
        self.horizontalLayout_15.addWidget(self.checkBoxWater)
        self.gridLayout_3.addLayout(self.horizontalLayout_15, 12, 0, 1, 1)
        self.dimensioningCheckBox = QtWidgets.QCheckBox(self.ThemesTab)
        self.dimensioningCheckBox.setTristate(True)
        self.dimensioningCheckBox.setObjectName("dimensioningCheckBox")
        self.gridLayout_3.addWidget(self.dimensioningCheckBox, 12, 1, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.mColorButton_14 = QgsColorButton(self.ThemesTab)
        self.mColorButton_14.setMinimumSize(QtCore.QSize(40, 10))
        self.mColorButton_14.setMaximumSize(QtCore.QSize(40, 10))
        self.mColorButton_14.setAcceptDrops(False)
        self.mColorButton_14.setColor(QtGui.QColor(145, 138, 111))
        self.mColorButton_14.setShowMenu(False)
        self.mColorButton_14.setObjectName("mColorButton_14")
        self.horizontalLayout_17.addWidget(self.mColorButton_14)
        self.checkBoxOrphan = QtWidgets.QCheckBox(self.ThemesTab)
        self.checkBoxOrphan.setTristate(True)
        self.checkBoxOrphan.setObjectName("checkBoxOrphan")
        self.horizontalLayout_17.addWidget(self.checkBoxOrphan)
        self.gridLayout_3.addLayout(self.horizontalLayout_17, 13, 0, 1, 1)
        self.locationCheckBox = QtWidgets.QCheckBox(self.ThemesTab)
        self.locationCheckBox.setTristate(True)
        self.locationCheckBox.setObjectName("locationCheckBox")
        self.gridLayout_3.addWidget(self.locationCheckBox, 13, 1, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.mColorButton_15 = QgsColorButton(self.ThemesTab)
        self.mColorButton_15.setMinimumSize(QtCore.QSize(40, 10))
        self.mColorButton_15.setMaximumSize(QtCore.QSize(40, 10))
        self.mColorButton_15.setAcceptDrops(False)
        self.mColorButton_15.setColor(QtGui.QColor(111, 92, 16))
        self.mColorButton_15.setShowMenu(False)
        self.mColorButton_15.setObjectName("mColorButton_15")
        self.horizontalLayout_18.addWidget(self.mColorButton_15)
        self.checkBoxOther = QtWidgets.QCheckBox(self.ThemesTab)
        self.checkBoxOther.setTristate(True)
        self.checkBoxOther.setObjectName("checkBoxOther")
        self.horizontalLayout_18.addWidget(self.checkBoxOther)
        self.gridLayout_3.addLayout(self.horizontalLayout_18, 14, 0, 1, 1)
        self.topoCheckBox = QtWidgets.QCheckBox(self.ThemesTab)
        self.topoCheckBox.setTristate(True)
        self.topoCheckBox.setObjectName("topoCheckBox")
        self.gridLayout_3.addWidget(self.topoCheckBox, 14, 1, 1, 1)
        self.tabWidget.addTab(self.ThemesTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.optionMsgDirButton = QtWidgets.QPushButton(self.groupBox)
        self.optionMsgDirButton.setMinimumSize(QtCore.QSize(0, 0))
        self.optionMsgDirButton.setObjectName("optionMsgDirButton")
        self.horizontalLayout_19.addWidget(self.optionMsgDirButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.textEditDirPreffered = QtWidgets.QTextEdit(self.groupBox)
        self.textEditDirPreffered.setMinimumSize(QtCore.QSize(20, 20))
        self.textEditDirPreffered.setMaximumSize(QtCore.QSize(1000, 100))
        self.textEditDirPreffered.setBaseSize(QtCore.QSize(200, 40))
        self.textEditDirPreffered.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditDirPreffered.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEditDirPreffered.setReadOnly(True)
        self.textEditDirPreffered.setObjectName("textEditDirPreffered")
        self.verticalLayout_2.addWidget(self.textEditDirPreffered)
        self.verticalLayout_3.addWidget(self.groupBox)
        spacerItem6 = QtWidgets.QSpacerItem(20, 318, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(B4UdigNL)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(B4UdigNL)

    def retranslateUi(self, B4UdigNL):
        _translate = QtCore.QCoreApplication.translate
        B4UdigNL.setWindowTitle(_translate("B4UdigNL", "KLIC Viewer"))
        self.messageBox.setTitle(_translate("B4UdigNL", "KLIC Berichten"))
        self.openMsgButton.setText(_translate("B4UdigNL", "&Open Folder..."))
        self.openArchiveButton.setText(_translate("B4UdigNL", "Open &Zip-bestand..."))
        self.gotoButton.setText(_translate("B4UdigNL", "&Ga naar"))
        self.bestScaleButton.setText(_translate("B4UdigNL", "Beste S&chaal"))
        self.removeMsgButton.setText(_translate("B4UdigNL", "&Sluit Bericht"))
        self.additionsBox.setTitle(_translate("B4UdigNL", "Bijlagen"))
        self.openDocButton.setText(_translate("B4UdigNL", "Open &Bijlage(n)"))
        self.saveButton.setText(_translate("B4UdigNL", "Opslaan in Project"))
        self.helpButton.setText(_translate("B4UdigNL", "&Help..."))
        self.closeButton.setText(_translate("B4UdigNL", "Afsl&uiten"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.messageTab), _translate("B4UdigNL", "Berichten"))
        self.checkBoxData.setText(_translate("B4UdigNL", "Datatransport"))
        self.refreshButton.setText(_translate("B4UdigNL", "&Ververs"))
        self.checkBoxGas_low.setText(_translate("B4UdigNL", "Gas lage druk"))
        self.checkBoxGas_high.setText(_translate("B4UdigNL", "Gas hoge druk"))
        self.checkBoxDanger.setText(_translate("B4UdigNL", "Buisleiding gevaarlijke inhoud"))
        self.checkBoxElec_land.setText(_translate("B4UdigNL", "Electriciteit landelijk  hoogspanningsnet"))
        self.checkBoxElec_high.setText(_translate("B4UdigNL", "Electriciteit hoogspanning"))
        self.checkBoxElec_mid.setText(_translate("B4UdigNL", "Electriciteit middenspanning"))
        self.checkBoxElec_low.setText(_translate("B4UdigNL", "Electriciteit laagspanning"))
        self.checkBoxChemical.setText(_translate("B4UdigNL", "(Petro) chemie"))
        self.vectorCheckBox.setText(_translate("B4UdigNL", "Vector"))
        self.checkBoxSewer_free.setText(_translate("B4UdigNL", "Riool vrij verval"))
        self.rasterCheckBox.setText(_translate("B4UdigNL", "Raster"))
        self.checkBoxSewer_pressure.setText(_translate("B4UdigNL", "Riool onder druk"))
        self.checkBoxHeat.setText(_translate("B4UdigNL", "Warmte"))
        self.annotationCheckBox.setText(_translate("B4UdigNL", "Annotatie"))
        self.checkBoxWater.setText(_translate("B4UdigNL", "Water "))
        self.dimensioningCheckBox.setText(_translate("B4UdigNL", "Maatvoering"))
        self.checkBoxOrphan.setText(_translate("B4UdigNL", "Wees"))
        self.locationCheckBox.setText(_translate("B4UdigNL", "Ligging"))
        self.checkBoxOther.setText(_translate("B4UdigNL", "Overig"))
        self.topoCheckBox.setText(_translate("B4UdigNL", "Topo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ThemesTab), _translate("B4UdigNL", "Thema\'s"))
        self.groupBox.setTitle(_translate("B4UdigNL", "KLIC Berichten"))
        self.optionMsgDirButton.setText(_translate("B4UdigNL", "Standaard folder..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("B4UdigNL", "Opties"))

##from qgscolorbutton import QgsColorButton
